### ISSUE TITLE
How to help?

### ISSUE THREAD

**Issue by lazarillo** [raskr/rust-autograd#14]
Hi @raskr 

I am very new to Rust and lower level programming, but not to tensors or differential equations. (I'm a data scientist.)

I'd like to help out in some way as a chance to work on my Rust skills while also doing something useful in a field I know/care about.

I saw that the project had been "asleep" for a while, but that you recently made a commit again.  Is there something in your mind that you'd like to tackle?

**Comment by raskr** [comment]
Thank you for your interest!
> Is there something in your mind that you'd like to tackle?

Most of what I initially intended to do has already been accomplished. (or rather, it has more functionality than I expected)
But I can't say there is nothing to do anymore, e.g.
- zero-copy tensor computations (now I'm trying)
- parallel graph execution
- model persistence
- more primitive ops
- more functional interface
...

Destructive changes to achieve these are welcome:)

**Comment by hegza** [comment]
I'm in a similar place with this as @lazarillo. I feel this library does really well a lot of the things that I currently need for my research. At least *I* am fairly convinced that this might be the best deferred computation graph library available in Rust at this moment.

I'm going to be using the library for another deep learning implementation, so perhaps I find something to contribute. I'm currently running a fork because I needed to expose the ndarray-0.10 internals, as I need to use some of the features from ndarray-0.12 separately.

I attempted to upgrade my fork to ndarray-0.12 but found it non-trivial enough to not be able to do it in an hour. I might be able to wrap my head around it if I get into the internals again.

Additionally, I'm working with OpenCL a lot (https://github.com/cogciprocate/ocl). I was wondering if the library interface can be made flexible enough to allow executing ops on a GPU. Parallel graph execution seems like a related topic.

**Comment by lazarillo** [comment]
Hi @raskr Thanks for the feedback!  Since I am new to Rust, I don't want to set my ambitions too high and crash.  I might look at the interface, as you suggest.  Many of the others look tough to tackle at the moment.  But first I think I'll spend some more time with the library and see what areas *I'd* like to improve, since it sounds like that would likely be most beneficial.

**Comment by oleg-kachan** [comment]
It seems you're interested to implement higher-order automatic differentiation.

Are you aware of [this paper](https://arxiv.org/abs/1812.11592)?

**Comment by raskr** [comment]
@oleg-kachan 
> Are you aware of this paper?

No, but all (probably) operations in this crate are already differentiable n-times.

**Comment by paulkernfeld** [comment]
👋 hey @raskr, I am another person who would like to help out! I would love to work on the issues that you listed above, but a lot of them might be too involved for me since I don't feel like I would be ready to make architecture decisions. The one that most caught my eye was, "more primitive ops." Do you have examples of primitive ops that you'd like to see added? I feel like that could be a good way to dip my toes in the water.

**Comment by raskr** [comment]
@paulkernfeld 
Sorry for the late reply!
> but a lot of them might be too involved for me since I don't feel like I would be ready to make architecture decisions.

Ah, it might be so as those thoughts are too sketchy. (but "model persistence", for example, could be implemented with only internal changes I think (with serde or protobuf? I don't know...).

> "more primitive ops." Do you have examples of primitive ops that you'd like to see added?

The first thing I envisioned for that is something that are implemented in theano, tensorflow or numpy but are not listed [here](https://docs.rs/autograd/1.0.0/autograd/struct.Graph.html) e.g.
- linalg ops (ref: https://numpy.org/doc/stable/reference/routines.linalg.html)
- conditional ops (np.where, np.argwhere, np.nonzero, ...)
- ops I forgot to implement (argmin, avg_pool, ... there's more probably :(
